site_name: Documentacion_Proyecto
site_url: https://DanielMarinhoMartinez.github.io/Documentacion_Proyecto/
docs_dir: 'docs_src'
site_dir: 'docs'
nav:
  - Manual de Usuario: Manual_de_Usuario.md
  - Guía de Referencia: Guia_de_Referencia.md
  - Guía de Instalación: Guia_de_Instalacion.md
